resolver: ghc-8.2.1
packages:
- inline-c
- inline-c-cpp
- sample-cabal-project
extra-deps:
- QuickCheck-2.10.0.1
- ansi-wl-pprint-0.6.7.3
- hashable-1.2.6.1
- mtl-2.2.1
- parsec-3.1.11
- parsers-0.12.5
- unordered-containers-0.2.8.0
- vector-0.12.0.1
- ansi-terminal-0.6.3.1
- attoparsec-0.13.1.0
- base-orphans-0.6
- cabal-doctest-1.0.2
- charset-0.3.7.1
- primitive-0.6.2.0
- random-1.1
- scientific-0.3.5.1
- text-1.2.2.2
- tf-random-0.5
- integer-logarithms-1.0.2
- semigroups-0.18.3
